{
 "title": "Gatling",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "influxdb" },
   {
    "name": "maxPlotPerSeries",
    "query": "1000, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000"
   },
   {
    "name": "lowerBound",
    "query": "800, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400, 2500"
   },
   {
    "name": "higherBound",
    "query": "1200, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 2300, 2400, 2500"
   },
   {
    "name": "percentile1",
    "query": "50, 10, 20, 30, 40, 50, 60, 70, 75, 80, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.9"
   },
   {
    "name": "percentile2",
    "query": "75, 10, 20, 30, 40, 50, 60, 70, 75, 80, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.9"
   },
   {
    "name": "percentile3",
    "query": "95, 10, 20, 30, 40, 50, 60, 70, 75, 80, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.9"
   },
   {
    "name": "percentile4",
    "query": "99, 10, 20, 30, 40, 50, 60, 70, 75, 80, 85, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99.5, 99.9"
   },
   { "name": "Filters" },
   {
    "name": "GlobalFilter",
    "query": "SHOW TAG KEYS FROM \"users\""
   },
   {
    "name": "GlobalFilter_values",
    "label": "Filter values",
    "query": "SHOW TAG VALUES FROM \"tests\" WITH KEY=\"$GlobalFilter\" WHERE $timeFilter"
   },
   {
    "name": "min_interval",
    "query": "SELECT ROUND(($__to - $__from) / ($maxPlotPerSeries + last(\"active\") - last(\"active\"))) from \"users\" "
   },
   {
    "name": "name",
    "label": "name",
    "query": "SHOW TAG VALUES FROM \"requests\" WITH KEY=\"name\" WHERE \"$GlobalFilter\" =~ /^${GlobalFilter_values:regex}$/ AND $timeFilter"
   }
  ]
 },
 "panels": [
  { "title": "🟣 Launches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tests",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "${GlobalFilter:raw}::tag" ], "type": "tag" },
      { "params": [ "action::tag" ], "type": "tag" },
      { "params": [ "simulation::tag" ], "type": "tag" },
      { "params": [ "systemUnderTest::tag" ], "type": "tag" },
      { "params": [ "testEnvironment::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tests",
     "select": [
      [
       { "params": [ "description" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "🟣 Response time ranges (${GlobalFilter} = ${GlobalFilter_values})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "t < ${lowerBound} ms",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "duration::field", "operator": "<", "value": "${lowerBound}" },
      { "condition": "AND", "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "alias": "t >= ${lowerBound} ms, t < ${higherBound} ms",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "duration::field", "operator": ">=", "value": "${lowerBound}" },
      { "condition": "AND", "key": "duration::field", "operator": "<", "value": "${higherBound}" },
      { "condition": "AND", "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "alias": "t >= ${higherBound} ms",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "duration::field", "operator": ">=", "value": "${higherBound}" },
      { "condition": "AND", "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "alias": "failed",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "OK",
     "groupBy": [
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "alias": "KO",
     "groupBy": [
      { "params": [ "result::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "✅ Summary (${GlobalFilter} = ${GlobalFilter_values})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "✅ Summary (OK)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "OK" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile1" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile1}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile2" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile2}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile3" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile3}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile4" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile4}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Std Dev" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "🛑 Errors (${GlobalFilter} = ${GlobalFilter_values})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "🛑 Summary (Errors)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "KO" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile1" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile1}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile2" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile2}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile3" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile3}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile4" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile4}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Std Dev" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "🛑 Summary (Errors with error messages)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "errorMessage::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "KO" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile1" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile1}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile2" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile2}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile3" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile3}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "$percentile4" ], "type": "percentile" },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "${percentile4}th pct" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" },
       { "params": [ "Std Dev" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "❇️ Active users over time (${GlobalFilter} = ${GlobalFilter_values})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "❇️ Active users over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "alias": "$tag_scenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "🟡 Response time distribution (${GlobalFilter} = ${GlobalFilter_values})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "🟡 Response time distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "alias": "OK",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "alias": "KO",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "${name} 🟡 Response time distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "repeat": "name",
   "targets": [
    {
     "alias": "OK",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "KO",
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "KO" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Response time percentiles over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 }
  },
  {
   "title": "🟡 Response time distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Active users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "90%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "85" ], "type": "percentile" },
       { "params": [ "85%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "80" ], "type": "percentile" },
       { "params": [ "80%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" },
       { "params": [ "75%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "50%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "${name} 🟡 Response time distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "repeat": "name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "90%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "85" ], "type": "percentile" },
       { "params": [ "85%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "80" ], "type": "percentile" },
       { "params": [ "80%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" },
       { "params": [ "75%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "50%" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "result::tag", "operator": "=", "value": "OK" },
      { "condition": "AND", "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  { "title": "Responses per second over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "❇️ Number of responses per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "result::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" }
     ]
    }
   ]
  },
  {
   "title": "${name} ❇️ Number of responses per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "repeat": "name",
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "result::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "${GlobalFilter}", "operator": "=~", "value": "/^$GlobalFilter_values$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  }
 ]
}